### ISSUE TITLE
Question about Table 3 benchmark result

### ISSUE THREAD

**Issue by lzjluzijie** [contact-discovery/disco#1]
![table](https://github.com/contact-discovery/disco/assets/7992620/86d14e31-5512-482f-9a48-4a5ada8b53a4)

The communication is 1072.14 MiB and bandwidth in the WiFi setting is 566mbit/s. Why it have 3.53 second setup time for `[44]`?

**Comment by cwb38** [comment]
Thanks for pointing this out! Indeed, we have reported the wrong numbers in those columns for [44]. This is now fixed in the ePrint version.
